POST http://localhost:3003/api/stories
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZWd1eSIsImlkIjoiNjcxMGY1OWIxOWJkMzNiNmU2Nzk3NjBjIiwiaWF0IjoxNzI5MzQ5MTI1fQ.Aun-eig_RqLIGev7xYyVw_2yvySYw6EPcXkQr8Oi-6Y 

{
    "author": "with authorization",
    "story": "new",
    "likes": 0,
    "comments": "comment1, comment2",
    "userId": "6710f59b19bd33b6e679760c"
}